services:
<<<<<<< HEAD

  streamvault:

    build: .

    ports:
      - "8087:8000"

=======
  streamvault:
    image: enrilinux/streamvault:latest
    ports:
      - 8087:8000
>>>>>>> b2d0c6e (second commit)
    volumes:
      - ./downloads:/app/downloads
